# Exercício:

## 01 – Obtenha os resultados e retorne o objeto e código em Python dos seguintes cálculos:
a) 2.0 + 3.0 / 5.0

b) (a + 10.2) - 5.0 * 2.0

c) a / b + 33.8

d) a / (b + c)

e) d * 2

In [3]:
a = 2.0 + 3.0 / 5.0
b = (a + 10.2) - 5.0 * 2.0
c = a / b + 33.8
d = a / (b + c)
e = d * 2 
print(a, b, c, d, e)

2.6 2.799999999999999 34.72857142857143 0.0692805481537876 0.1385610963075752


## 02 – Obtenha os resultados e retorne o código do objeto em Python dos seguintes cálculos:
a) [2.0, 3.0, 5.0] + [10, 20, 30]

b) lista_a * 2

c) lista_a + lista_b

d) lista_a / (lista_b * lista_c)

In [16]:
a2 = [2.0, 3.0, 5.0] + [10, 20, 30]
b2 = a2 * 2
c2 = a2 + b2
d2 = a2 / (b2 * c2)

TypeError: can't multiply sequence by non-int of type 'list'

In [17]:
# retornando resultado apenas de a2, b2 e c2 pois o d2 apresenta erro na multiplicação de não inteiros em lista. 
print(a2, b2, c2)

[2.0, 3.0, 5.0, 10, 20, 30] [2.0, 3.0, 5.0, 10, 20, 30, 2.0, 3.0, 5.0, 10, 20, 30] [2.0, 3.0, 5.0, 10, 20, 30, 2.0, 3.0, 5.0, 10, 20, 30, 2.0, 3.0, 5.0, 10, 20, 30]


## 03 – Usando os objetos simples obtidos no exercício 01 (a, b, c, d, e), instancie uma  lista. Instancie também uma segunda lista contendo a raiz quadrada dos valores obtidos nos objetos simples. Instancie uma terceira lista, concatenando as duas primeiras. Recupere a última lista.

In [24]:
questao3 = [a, b, c, d, e]
raiz = [(a ** 0.5), (b ** 0.5), (c ** 0.5), (d ** 0.5), (e ** 0.5)]
concateado = [questao3 + raiz]
concateado

[[2.6,
  2.799999999999999,
  34.72857142857143,
  0.0692805481537876,
  0.1385610963075752,
  1.61245154965971,
  1.6733200530681507,
  5.893095233285427,
  0.263211983302029,
  0.3722379565648501]]

## 04 – Duplique os valores contidos na lista final obtida no exercício anterior e converta para um array numpy. Remodele (reshape) o array, para que contenha 5 linhas e 4 colunas. Recupere o array.

In [27]:
import numpy as np

In [35]:
questao4 = concateado * 2
array = np.array(questao4)
array = np.array(questao4).reshape(5, 4)
array

array([[ 2.6       ,  2.8       , 34.72857143,  0.06928055],
       [ 0.1385611 ,  1.61245155,  1.67332005,  5.89309523],
       [ 0.26321198,  0.37223796,  2.6       ,  2.8       ],
       [34.72857143,  0.06928055,  0.1385611 ,  1.61245155],
       [ 1.67332005,  5.89309523,  0.26321198,  0.37223796]])

## 05 – Do array numpy obtenha uma lista contendo a média dos valores de cada uma das colunas.

In [43]:
media05 = [array.mean(axis= 0)]
media05

[array([7.88073291, 2.14941306, 7.88073291, 2.14941306])]

## 06 – Insira as médias das colunas no final do array do exercício 4.

**Contexto:**
- No exercício 4, você criou um array numpy com 5 linhas e 4 colunas (totalizando 20 valores)
- No exercício 5, você calculou a média de cada uma das 4 colunas (resultando em uma lista com 4 valores)

**Tarefa:**
1. Use o atributo `shape` do array do exercício 4 para calcular o número total de elementos.
2. Insira a lista de médias (do exercício 5) no final de outro array criado
3. Recupere e exiba o array resultante


Obs.:  Atributos não usam () na chamada.

In [45]:
# 1 calcular numero de elementos
array.shape
total = 5 * 4
total

20

In [58]:
# 2 inserir lista de média em novo array e recuperar array resultante
array2 = np.concatenate([array] + [media05])
array2

array([[ 2.6       ,  2.8       , 34.72857143,  0.06928055],
       [ 0.1385611 ,  1.61245155,  1.67332005,  5.89309523],
       [ 0.26321198,  0.37223796,  2.6       ,  2.8       ],
       [34.72857143,  0.06928055,  0.1385611 ,  1.61245155],
       [ 1.67332005,  5.89309523,  0.26321198,  0.37223796],
       [ 7.88073291,  2.14941306,  7.88073291,  2.14941306]])

## 07 – Remodele (reshape) o array do exercício anterior, para que contenha 4 colunas. Converta este objeto da classe array para DataFrame. Arredonde todos os valores para até 3 casas decimais. Recupere a DataFrame.

In [63]:
array3 = np.array(array2).reshape(6, 4)
array3

array([[ 2.6       ,  2.8       , 34.72857143,  0.06928055],
       [ 0.1385611 ,  1.61245155,  1.67332005,  5.89309523],
       [ 0.26321198,  0.37223796,  2.6       ,  2.8       ],
       [34.72857143,  0.06928055,  0.1385611 ,  1.61245155],
       [ 1.67332005,  5.89309523,  0.26321198,  0.37223796],
       [ 7.88073291,  2.14941306,  7.88073291,  2.14941306]])

In [66]:
import pandas as pd

In [123]:
df = pd.DataFrame(array3)
df = df.round(3)
df

,0,1,2,3
0,2.600,2.800,34.729,0.069
1,0.139,1.612,1.673,5.893
2,0.263,0.372,2.600,2.800
3,34.729,0.069,0.139,1.612
4,1.673,5.893,0.263,0.372
5,7.881,2.149,7.881,2.149


## 08 – A última instancia desta DataFrame deve conter as médias dos valores contidos por coluna, o que foi determinado nos exercícios anteriores. Instancie um objeto contendo as médias dos valores em cada linha. Insira este objeto como uma nova coluna na DataFrame. Recupere a DataFrame.

In [125]:
medias_linhas = df.mean(1)
medias_linhas

0    10.04950
1     2.32925
2     1.50875
3     9.13725
4     2.05025
5     5.01500
dtype: float64

In [126]:
df["media"] = medias_linhas
df

,0,1,2,3,media
0,2.600,2.800,34.729,0.069,10.04950
1,0.139,1.612,1.673,5.893,2.32925
2,0.263,0.372,2.600,2.800,1.50875
3,34.729,0.069,0.139,1.612,9.13725
4,1.673,5.893,0.263,0.372,2.05025
5,7.881,2.149,7.881,2.149,5.01500


## 09 – Usando o método dos objetos de classe DataFrame, describe(), compare os resultados contidos na última linha e última coluna da DataFrame.

Obs.: O método dos objetos de classe DataFrame, transpose(), inverte linhas por colunas.

In [127]:
df1 = df.describe()
df1

,0,1,2,3,media
count,6.000000,6.000000,6.000000,6.000000,6.000000
mean,7.880833,2.149167,7.880833,2.149167,5.015000
std,13.455228,2.107787,13.455228,2.107787,3.758615
min,0.139000,0.069000,0.139000,0.069000,1.508750
25%,0.615500,0.682000,0.615500,0.682000,2.120000
50%,2.136500,1.880500,2.136500,1.880500,3.672125
75%,6.560750,2.637250,6.560750,2.637250,8.106688
max,34.729000,5.893000,34.729000,5.893000,10.049500


In [128]:
df2 = df.transpose().describe()
df2

,0,1,2,3,4,5
count,5.000000,5.000000,5.000000,5.000000,5.00000,5.000
mean,10.049500,2.329250,1.508750,9.137250,2.05025,5.015
std,14.289318,2.147244,1.193969,14.788245,2.28691,2.866
min,0.069000,0.139000,0.263000,0.069000,0.26300,2.149
25%,2.600000,1.612000,0.372000,0.139000,0.37200,2.149
50%,2.800000,1.673000,1.508750,1.612000,1.67300,5.015
75%,10.049500,2.329250,2.600000,9.137250,2.05025,7.881
max,34.729000,5.893000,2.800000,34.729000,5.89300,7.881


In [129]:
ultima_linha = df1.iloc[-1]
ultima_coluna = df2.iloc[-1]
print(ultima_linha)
print(ultima_coluna)

0        34.7290
1         5.8930
2        34.7290
3         5.8930
media    10.0495
Name: max, dtype: float64
0    34.729
1     5.893
2     2.800
3    34.729
4     5.893
5     7.881
Name: max, dtype: float64


In [130]:
ultima_coluna.equals(ultima_linha)

False

## 10 – Edite o nome das colunas e dos index, para indicar onde estão as médias. Qual a média das médias?

In [132]:
df.rename(index={df.index[-1]: "media"}, inplace=True)
df

,0,1,2,3,media
0,2.600,2.800,34.729,0.069,10.04950
1,0.139,1.612,1.673,5.893,2.32925
2,0.263,0.372,2.600,2.800,1.50875
3,34.729,0.069,0.139,1.612,9.13725
4,1.673,5.893,0.263,0.372,2.05025
media,7.881,2.149,7.881,2.149,5.01500


A média das médias está na ultima coluna e ultima linha: 5,01500

In [121]:
df.to_csv('q10exercicio7.csv')