# Exercício:

## 01 – Obtenha os resultados e retorne o código Python dos seguintes cálculos:

<br>a = 2.0 + 3.0 / 5.0 == 10
<br>b = (a + 10.2) - 5.0 * 2.0 <= 2.9
<br>c = 10 <= a / b + 33.8 < 100
<br>d = 5 != a / (b + c)
<br>e = 33 == d * 2

In [18]:
a = 2.0 + 3.0 / 5.0 == 10
b = (a + 10.2) - 5.0 * 2.0 <= 2.9
c = 10 <= a / b + 33.8 < 100
d = 5 != a / (b + c)
e = 33 == d * 2
print(a,b,c,d,e)

False True True True False


## 02 – Altere os operadores relacionais para modificar o resultado de cada uma das comparações.

<br>('a',1,True,'b',0,False) != ('a',True,1,'b',False,0)
<br>['a',1,True,'b',0,False] != ('a',True,1,'b',False,0)
<br>['a',1,True,'b',0,False] != ['a',True,1,'b',False,0]
<br>['a',1,True,'b',0,False] > ['a',True,1]
<br>['a',1,True,'b',0,False] == 1
<br>['a',True,1] <= ['a',True,1] < ['a',1,True,'b',0,False]

In [19]:
('a',1,True,'b',0,False) == ('a',True,1,'b',False,0)
['a',1,True,'b',0,False] == ('a',True,1,'b',False,0)
['a',1,True,'b',0,False] == ['a',True,1,'b',False,0]
['a',1,True,'b',0,False] < ['a',True,1]
['a',1,True,'b',0,False] != 1
['a',True,1] <= ['a',True,1] > ['a',1,True,'b',0,False]

False

## 03 – Usando o método DataFrame.to_csv(‘nome_do_arquivo.csv’) exporte o objeto obtido no exercício 10 da aula anterior para um arquivo CSV. Usando o método pd.read_csv(‘nome_do_arquivo.csv’) instancie uma DataFrame. Use o valor ‘Unnamed: 0’ no parâmetro index_col, para ajustar o index. Arredonde os valores para até três casas decimais, usando o método round().
Recupere a DataFrame.

In [20]:
import pandas as pd

In [21]:
df = pd.read_csv("q10exercicio7.csv", index_col="Unnamed: 0")
df = df.round(3)
df

,0,1,2,3,media
0,2.600,2.800,34.729,0.069,10.049
1,0.139,1.612,1.673,5.893,2.329
2,0.263,0.372,2.600,2.800,1.509
3,34.729,0.069,0.139,1.612,9.137
4,1.673,5.893,0.263,0.372,2.050
media,7.881,2.149,7.881,2.149,5.015


## 04 – Instancie um numpy array que apresente o mesmo formato (linhas e colunas) da DataFrame. Este array deve conter apenas inteiros uns.
Recupere o array.

Obs.: Procure na internet o método numpy.ones()

In [22]:
import numpy as np

In [23]:
array = np.ones((6, 5))
array

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

## 05 – Quantos dos valores contidos na DataFrame são iguais aos valores no array?

In [24]:
df_array = df.to_numpy()
df_array

array([[ 2.6  ,  2.8  , 34.729,  0.069, 10.049],
       [ 0.139,  1.612,  1.673,  5.893,  2.329],
       [ 0.263,  0.372,  2.6  ,  2.8  ,  1.509],
       [34.729,  0.069,  0.139,  1.612,  9.137],
       [ 1.673,  5.893,  0.263,  0.372,  2.05 ],
       [ 7.881,  2.149,  7.881,  2.149,  5.015]])

In [25]:
valores_iguais = (df.to_numpy() == array).sum()
valores_iguais

np.int64(0)

## 06 – Quantos dos valores contidos na DataFrame são superiores aos valores no array?

In [26]:
maiores = (df.to_numpy() > array).sum()
maiores

np.int64(22)

## 07 – Quantos dos valores contidos na DataFrame são iguais ou inferiores aos valores no array?

In [27]:
iguais_inferiores = ((df.to_numpy() == array).sum() or (df.to_numpy() < array).sum())
iguais_inferiores

np.int64(8)

## 08 – Quantos dos valores contidos na DataFrame estão entre 0 e 1?

In [28]:
((df >= 0) & (df <= 1)).sum().sum()

np.int64(8)

## 09 – Quantos dos valores das médias das linhas são inferiores ou iguais à 5?

Obs 1.: Usando o método de classe, você pode converter qualquer objeto em outra classe. Ex. obj = list(array)

Obs 2.: Assim com o objeto da classe str, listas também possuem a função count()

In [44]:
medias9 = list(df_array)
medias5v= medias9[5]
medias5v

array([7.881, 2.149, 7.881, 2.149, 5.015])

In [ ]:
quantidade = sum(1 for x in medias5v if x <= 5)
quantidade

2

In [50]:
quantidade2 = [x <= 5 for x in medias5v].count(True)
quantidade2

2

## 10 – Quantos dos valores das médias das colunas são superiores à 5?

In [52]:
ultima_coluna = df_array[:, -1].tolist()
ultima_coluna

[10.049, 2.329, 1.509, 9.137, 2.05, 5.015]

In [54]:
quantidade10 = [x > 5 for x in ultima_coluna].count(True)
quantidade10

3